[SC-296] Update Spark alerts
marsfoundation/sparklend-monitoring pull request #6
Opened 2023-12-15 18:39 UTC by barrutko

2023-12-18 19:35 UTC, lucas-manuel requested changes

2023-12-18 19:35 UTC, lucas-manuel commented on actions/src/monitor-sparklend.ts
> +				/ BigInt(10**decimalsSheet[log.args.reserve])
`10 ** decimalsSheet[log.args.reserve]`, apply to all `**`

2023-12-18 19:35 UTC, lucas-manuel commented on actions/src/monitor-sparklend.ts
> +				/ BigInt(10**6),
Add note to say that we're dividing by 1e6 rather than 1e8 because we want the value in cents.

2023-12-18 19:35 UTC, lucas-manuel commented on actions/src/monitor-sparklend.ts
> +Value:  $ ${formatBigInt(BigInt(log.args.amount)
I don't think these values will be aligned as is, maybe I'm missing something

2023-12-19 12:12 UTC, barrutko commented on actions/src/monitor-sparklend.ts
> +Value:  $ ${formatBigInt(BigInt(log.args.amount)
```
BORROW

Account 0xdceed643320622cad92b7a90465e24d7df0a9519 performed a borrow interaction.

Transaction hash: 0x858ec525946029a18ef12e5bd8419614f6a533f57bf945420ed56e201324e233
(https://etherscan.io/tx/0x858ec525946029a18ef12e5bd8419614f6a533f57bf945420ed56e201324e233)

TRANSACTION DETAILS:
Asset:  DAI (0x6B175474E89094C44Da98b954EedeAC495271d0F)
Amount:   2,000,000.000000000000000000 DAI
Value:  $ 1,999,697.50
```

2023-12-19 12:12 UTC, barrutko commented on actions/src/monitor-sparklend.ts
> +Value:  $ ${formatBigInt(BigInt(log.args.amount)
It looks like this. I think it's ok for now.

2023-12-19 12:16 UTC, barrutko commented on actions/src/monitor-sparklend.ts
> +Value:  $ ${formatBigInt(BigInt(log.args.amount)
It doesn't look as good for non-stablecoins, but I think it's ok for now. I'm gonna be changing this message soon anyway.

2023-12-19 12:53 UTC, lucas-manuel commented on actions/src/monitor-sparklend.ts
> +Value:  $ ${formatBigInt(BigInt(log.args.amount)
Ah yeah I see what you did now but yeah I think it should look like this:


```
BORROW

Account 0xdceed643320622cad92b7a90465e24d7df0a9519 performed a borrow interaction.

Transaction hash: 0x858ec525946029a18ef12e5bd8419614f6a533f57bf945420ed56e201324e233
(https://etherscan.io/tx/0x858ec525946029a18ef12e5bd8419614f6a533f57bf945420ed56e201324e233)

TRANSACTION DETAILS:
Asset:  DAI (0x6B175474E89094C44Da98b954EedeAC495271d0F)
Amount: 2,000,000.000000000000000000
Value:  $1,999,697.50
```

Because yeah that alignment approach is only relenavt for stables.

2023-12-19 15:31 UTC, lucas-manuel approved these changes

2023-12-19 15:31 UTC, merged